import React from 'react'
import Head from 'next/head'

export default function Header({ item }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet" />
            </Head>
            <div className='header-section'>
                <h1>Demo Streaming</h1>
                <div className='dummy-nav'>
                    <p>Log in</p>
                    <p className='login-btn'>Start your free trail</p>
                </div>
            </div>
            <div className='header-step'>{`Popular ${item}`}</div>
        </>
    )
}
